language: php
php:
  - 5.4

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2
  - composer self-update && composer --version
  - composer update --dev

script: phpunit --coverage-text --configuration tests/phpunit.xml tests/

notifications:
  email:
    - dev@funivan.com